sonar.projectKey=github-gists-api
sonar.projectName=GitHub Gists API
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.coverage.exclusions=tests/**/*.py
sonar.sourceEncoding=UTF-8
sonar.language=python
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=target/test-results/report.xml
